### ISSUE TITLE
NullPointerExeption in LocationAjaxCallback

### ISSUE THREAD

**Issue by stepango** [tinyeeliu/androidquery#16]
I receive this stacktrace from my app on Google Play. Lib ver 0.21.5

java.lang.NullPointerException
 at com.androidquery.callback.LocationAjaxCallback.stop(LocationAjaxCallback.java:206)
 at com.androidquery.callback.LocationAjaxCallback.check(LocationAjaxCallback.java:107)
 at com.androidquery.callback.LocationAjaxCallback.access$0(LocationAjaxCallback.java:85)
 at com.androidquery.callback.LocationAjaxCallback$Listener.onLocationChanged(LocationAjaxCallback.java:283)
 at android.location.LocationManager$ListenerTransport._handleMessage(LocationManager.java:227)
 at android.location.LocationManager$ListenerTransport.access$000(LocationManager.java:160)
 at android.location.LocationManager$ListenerTransport$2.handleMessage(LocationManager.java:183)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loop(Looper.java:123)
 at android.app.ActivityThread.main(ActivityThread.java:3701)
 at java.lang.reflect.Method.invokeNative(Native Method)
 at java.lang.reflect.Method.invoke(Method.java:507)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:624)
 at dalvik.system.NativeStart.main(Native Method)

**Comment by tinyeeliu** [comment]
thanks for reporting will look into it.

sent from mobile
On May 22, 2012 12:48 AM, "stepango" <
reply@reply.github.com>
wrote:

**Comment by tinyeeliu** [comment]
Fixed for future release. Thanks for reporting. :)
