### ISSUE TITLE
Context = null

### ISSUE THREAD

**Issue by stepango** [tinyeeliu/androidquery#26]
Aquery v0.22.10

in list adapter:

AQuery aq = listAq.recycle(convertView);
Bitmap placeholder = aq.getCachedImage(R.drawable.image_ph);

returns NullPointerException.

For avoiding it i need to use smth like 

aq.id(R.id.name).text(photo.title);

after recycle method. But it doesnot make sence if i need only async Image loading in this adapter.

Full stack trace:

08-05 14:40:11.513: ERROR/AndroidRuntime(9947): FATAL EXCEPTION: main
        java.lang.NullPointerException
        at com.androidquery.callback.BitmapAjaxCallback.getMemoryCached(BitmapAjaxCallback.java:384)
        at com.androidquery.AbstractAQuery.getCachedImage(AbstractAQuery.java:2030)
        at fm.soundtracker.ui.AsyncItemAdapter.getView(AsyncItemAdapter.java:47)
        at android.widget.AbsListView.obtainView(AbsListView.java:2040)
        at android.widget.GridView.onMeasure(GridView.java:1041)
        at android.view.View.measure(View.java:12881)
        at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:599)
        at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:381)
        at android.view.View.measure(View.java:12881)

**Comment by tinyeeliu** [comment]
Couldn't reproduce. What aq version you are using?

**Comment by stepango** [comment]
It's my misstake. It happens when convertView = null. Sorry for take your time.
